### ISSUE TITLE
Question: graph input for polished flye assembly

### ISSUE THREAD

**Issue by ZarulHanifah** [metagentools/MetaCoAG#2]
Hello MetaCoAG developers,

Fantastic idea for using the assembly graphs for binning, and even more fantastic that it can accept Flye assemblies.. But my Flye assemblies have passed through a number of polishing using medaka, racon, etc. So the contigs are different than the flye graph assembly... What should I do then?

**Comment by Vini2** [comment]
Hello @ZarulHanifah,

Thanks for your interest in our binning tool. 

I'm not very familiar with the level of difference between the original contigs and the polished contigs. If you can find the correspondence between the original contigs and the polished contigs, you can still use MetaCoAG as long as their contig names match.  

We are in the process of testing long-read assemblies and will provide an updated version soon.

Best regards,
Vijini

**Comment by hdore** [comment]
Hello @Vini2 
Thank you for this new tool, I've been trying Graphbin but I was waiting for a tool using the assembly graph directly for binning!

I'm also using polished assemblies from long reads. It's easy (at least in my case) to trace back the polished contigs to the contigs in Flye output, but not to the edges that are in the graph (because I polished the final contigs and not the edges from the gfa). I know you're working on a version to use Flye final contigs, I'm just curious to know how you plan to implement it? Will it simply flag the edges that are not in the contig file to avoid binning them?

Thanks, and I'll be using this new version as soon as it's out :) 

Hugo

**Comment by Vini2** [comment]
Hello @hdore,

I'm extremely sorry for getting back to you late.

Thank you very much for trying out GraphBin. 

Flye provides the graph path with edges for each contig (in the `assembly_info.txt` file) which I can use to build a graph with contigs. MetaCoAG can use this graph for binning. I will be able to publish a new release by next week.

Thank you very much for your interest in MetaCoAG and I would appreciate your input to improve MetaCoAG.

Best regards,
Vijini

**Comment by KatharinaHoff** [comment]
Thank you for developing this tool. I would like to try it with a MetaFlye assembly.

Should I wait for the beforementioned release (didn't see it tagged, yet) to use Flye assembler as input, or can I use the current repository code for this?

**Comment by emilyjunkins** [comment]
Hello,

Like the others here , I am also using a polished long read assemblies (nanopore+illumina), is there still a version of Graphbin coming that can use the final Fyle contigs?

**Comment by Vini2** [comment]
Hello @ZarulHanifah, @hdore, @KatharinaHoff and @emilyjunkins,

I have updated MetaCoAG to handle the original Flye assembly graph with contigs in commit [5bb24c4c371932f334aeee2edae283f1af5285f1](https://github.com/metagentools/MetaCoAG/commit/5bb24c4c371932f334aeee2edae283f1af5285f1). 

Let me know how if you have any further questions.

Thank you!

**Comment by Vini2** [comment]
Closing this issue after adding the feature.
